NewsPaper/NewsPaper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers

from news.views import PostViewSet
from .yasg import urlpatterns as doc_urls

router = routers.DefaultRouter()
router.register(r'post', PostViewSet)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('news.urls')),
    path('api/v1/', include(router.urls)),
    # path('api/v1/postlist/', PostViewSet.as_view({'get': 'list'})),
    # path('api/v1/postlist/<int:pk>/', PostViewSet.as_view({'put': 'update'})),
    path('api/v1/api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += doc_urls

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

NewsPaper/news/urls.py
from django.urls import path

from .views import IndexView, PostDetails, PostCreate, PostFind, PostEdit, PostDelete, \
    AuthorEdit, request_upgrade_group, subscribe_category, unsubscribe_category, \
    CategoryView, like_article, dislike_article, ArchiveView, set_timezone, \
    set_local_for_user

app_name = 'news'
urlpatterns = [
    # Classes views
    path('', IndexView.as_view(), name='index'),
    # path('news/', NewsView.as_view(), name='news'),
    # path('articles/', ArticlesView.as_view(), name='articles'),
    path(
        'caterory/<int:pk>/', CategoryView.as_view(),
        name='category'
    ),
    path(
        'archive/<int:year>/<int:month>/', ArchiveView.as_view(),
        name='archive'
    ),
    path('<int:pk>/', PostDetails.as_view(), name='detail'),
    path('create/', PostCreate.as_view(), name='create'),
    path('search/', PostFind.as_view(), name='search'),
    path('edit/<int:pk>/', PostEdit.as_view(), name='edit'),
    path('delete/<int:pk>/', PostDelete.as_view(), name='delete'),
    path('profile/<int:pk>/', AuthorEdit.as_view(), name='profile'),
    # Functions views
    path('req_to_author/', request_upgrade_group, name='req_to_author'),
    path('subscribe_cat/<int:post_cat>/', subscribe_category),
    path('unsubscribe_cat/<int:post_cat>/', unsubscribe_category),
    path('set_tz/', set_timezone),
    path('save_local/', set_local_for_user),

    path('like_post/<int:pk>/', like_article),
    path('dislike_post/<int:pk>/', dislike_article),
]

NewsPaper/news/views.py
from datetime import timedelta

import django_filters
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import User, Group
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_list_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, DeleteView, UpdateView, \
    ListView, DetailView

from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response

from .fiters import PostFilter
from .form import PostingForm, UserForm
from .models import Post, Author, Comment, Category, PostCategory
from .permissions import PermissionAndOwnerRequiredMixin, \
    ProfileOwnerRequiredMixin, IsOwnerOrReadOnly, IsAuthorOrReadOnly
from .serializers import PostSerializer


class IndexView(ListView):
    """Вывод всех новостей и статей"""
    queryset = Post.objects.select_related().all().order_by('-pk')
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 10


class ArchiveView(ListView):
    """Вывод новостей и статей за определенный год и месяц"""
    model = Post
    template_name = 'archive.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        year = self.kwargs.get('year', None)
        month = self.kwargs.get('month', None)
        queryset = get_list_or_404(
            Post.objects.select_related().order_by('-date_pub').filter(
                date_pub__year=year, date_pub__month=month
            )
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['month'] = self.kwargs.get('month', None)
        context['year'] = self.kwargs.get('year', None)
        return context


class CategoryView(ListView):
    """Вывод статей определенной категории"""
    model = Post
    template_name = 'category.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        cat_id = self.kwargs['pk']
        queryset = get_list_or_404(
            Post.objects.select_related().filter(post_cat=cat_id).order_by('-date_pub')
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Получаем имя категории
        cat_id = self.kwargs.get('pk', None)
        context['cat_name'] = get_list_or_404(PostCategory.objects.filter(cat=cat_id))[0]

        # Добавление контекста для подписки
        context['post_category'] = PostCategory.objects.filter(
            cat=cat_id
        ).select_related()[:1]
        context['is_subscribed'] = Category.objects.filter(
            subscribers=self.request.user.id
        ).values_list('name', flat=True)
        return context


class PostDetails(DetailView):
    """Вывод выбранной статьи"""
    queryset = Post.objects.all().select_related()
    template_name = 'detail.html'
    context_object_name = 'content'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Подтягиваем комментарии к статье
        context['comments'] = Comment.objects.select_related().filter(
            post_id=self.kwargs['pk']
        )
        # Добавление контекста для подписки
        context['post_category'] = PostCategory.objects.filter(
            post_id=self.object.pk
        ).select_related()
        context['is_subscribed'] = Category.objects.filter(
            subscribers=self.request.user.id
        ).values_list('name', flat=True)
        return context


class PostFind(ListView):
    """Поиск по сайту"""
    model = Post
    ordering = '-date_pub'
    template_name = 'search.html'
    context_object_name = 'search'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.postfilter = PostFilter(self.request.GET, queryset)
        return self.postfilter.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['postfilter'] = self.postfilter
        return context


class PostCreate(PermissionRequiredMixin, CreateView):
    """Добавление Статьи/Новости"""
    permission_required = (
        'news.add_post',
    )
    context_object_name = 'create'
    form_class = PostingForm
    model = Post
    template_name = 'edit.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        # Добавляем текущего пользователя в форму
        self.object.author_post = Author.objects.get(
            author_user=self.request.user
        )
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Проверяем количество постов автора за текущие сутки
        limit = settings.DAILY_POST_LIMIT
        context['limit'] = limit
        last_day = timezone.now() - timedelta(days=1)
        posts_day_count = Post.objects.filter(
            author_post__author_user=self.request.user,
            date_pub__gte=last_day,
        ).count()
        context['count'] = posts_day_count
        context['post_limit'] = posts_day_count < limit
        return context


class PostEdit(PermissionAndOwnerRequiredMixin, UpdateView):
    """Изменение Статьи/Новости"""
    # Используется доработанный миксин - с контролем владельца
    permission_required = (
        'news.change_post',
    )
    form_class = PostingForm
    model = Post
    context_object_name = 'edit'
    template_name = 'edit.html'


class PostDelete(PermissionAndOwnerRequiredMixin, DeleteView):
    """Удаление Статьи/Новости"""
    # Используется доработанный миксин - с контролем владельца
    permission_required = (
        'news.delete_post',
    )
    model = Post
    context_object_name = 'delete'
    template_name = 'delete.html'
    success_url = reverse_lazy('news:index')


class AuthorEdit(ProfileOwnerRequiredMixin, UpdateView):
    """Редактирование профиля пользователя"""
    # Используется доработанный миксин - с контролем владельца
    permission_required = (
        'auth.change_user',
        'account.change_emailaddress',
    )
    form_class = UserForm
    model = User
    context_object_name = 'profile'
    template_name = 'profile.html'
    success_url = reverse_lazy('news:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_author'] = \
            self.request.user.groups.filter(name='authors').exists()
        return context


@login_required
def request_upgrade_group(request):
    """Добавление пользователя в группу authors"""
    user = request.user
    author_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        author_group.user_set.add(user)
    return redirect(f'/profile/{user.id}/')


@login_required
def subscribe_category(request, post_cat):
    """Подписка на новости в категории"""
    user = request.user
    category = Category.objects.get(pk=post_cat)
    is_subscribed = category.subscribers.filter(id=user.id).exists()
    if not is_subscribed:
        # Добавляем подписчика в базу и
        # отправляем письмо об успешной подписке
        category.subscribers.add(user)
        html_content = render_to_string(
            'email/cat_subscribe.html',
            {
                'user': user,
                'category': category.name,
            }
        )
        message = EmailMultiAlternatives(
            subject=f'{user}, подписка на новости {category.name} оформлена!',
            from_email=settings.EMAIL,
            to=[user.email],
        )
        message.attach_alternative(html_content, 'text/html')
        try:
            message.send()
        except Exception as e:
            print(e)
        finally:
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def unsubscribe_category(request, post_cat):
    """Отписка от рассылки новостей в категории"""
    user = request.user
    category = Category.objects.get(pk=post_cat)
    is_subscribed = category.subscribers.filter(id=user.id).exists()
    if is_subscribed:
        category.subscribers.remove(user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def like_article(request, pk):
    """Увеличение рейтинга статьи, обновление рейтинга автора"""
    liked_post = Post.objects.get(pk=pk)
    author_id = liked_post.author_post.id
    author = Author.objects.get(pk=author_id)
    liked_post.like()
    author.update_rate()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def dislike_article(request, pk):
    """Уменьшение рейтинга статьи, обновление рейтинга автора"""
    disliked_post = Post.objects.get(pk=pk)
    author_id = disliked_post.author_post.id
    author = Author.objects.get(pk=author_id)
    disliked_post.dislike()
    author.update_rate()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def set_timezone(request):
    """Установка часового пояса"""
    if request.POST:
        request.session['django_timezone'] = request.POST['timezone']
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def set_local_for_user(request):
    """Сохранение локальных настроек для пользователя"""
    if request.POST:
        user_local = Author.objects.get(author_user_id=request.user.id)
        user_local.timezone = request.POST.get("tz")
        user_local.language = request.POST.get("lg")
        user_local.save()

NewsPaper/templates/articles.html
{% extends 'default.html' %}

{% load censor %}
{% load news_tags %}

{% block title %}Статьи{% endblock title %}

{% block content %}
<table class="news">
    <tr>
        <th>Последние статьи</th>
    </tr>
    <tr>
        <td>
            <table>
            {% for nw in articles %}
            <tr>
                <td>
                    <p class="metanews">
                        {{ nw.author_post }}, {{ nw.date_pub|date:'d.m.Y' }}:
                    </p>
                    <a class="news_title" href="{% url 'news:detail' nw.id %}">
                        {{ nw.name|censor }}
                    </a>
                    <br>
                    <p>{{ nw.content|censor|truncatechars:250|safe }}</p>
                </td>
            </tr>
            {% endfor %}
            </table>
        </td>
    </tr>
</table>
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}"><<&nbsp;</a>
        <a href="?{% url_replace page=page_obj.previous_page_number %}"><&nbsp;</a>
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1  %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    <span class="current">&nbsp;{{ page_obj.number }}&nbsp;</span>

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">&nbsp;></a>
        <a href="?{% url_replace page=page_obj.paginator.num_pages %}">&nbsp;>></a>
    {% endif %}
</div>

{% endblock content %}

NewsPaper/templates/category.html
{% extends 'default.html' %}
{% load i18n %}
{% load news_filters %}
{% load news_tags %}
{% block title %}Cтатьи в категории {{ cat_name }}{% endblock title %}
{% block content %}

    <h4 class="pb-1 mb-4 fst-italic">
        {% blocktrans with cat_name as cat_name %}Публикации в категории "{{ cat_name }}"{% endblocktrans %}

        {% for cat in post_category %}
            {% if cat.cat.name not in is_subscribed %}
                <div class="container text-end">
                    <div class="btn-group btn-group-sm" role="group">
{#                        <button type="button" class="btn btn-primary disabled">{{ cat.cat.name }}</button>#}
                        <button type="button" class="btn btn-success">
                            <a class="text-decoration-none text-light" href="/subscribe_cat/{{ cat.cat_id }}/">{% trans "Подписаться на новости в категории" %}</a>
                        </button>
                    </div>
                </div>
            {% elif cat.cat.name in is_subscribed %}
                <div class="container text-end">
                    <div class="btn-group btn-group-sm" role="group">
{#                        <button type="button" class="btn btn-primary disabled">{{ cat.cat.name }}</button>#}
                        <button type="button" class="btn btn-danger">
                            <a class="text-decoration-none text-light" href="/unsubscribe_cat/{{ cat.cat_id }}/">{% trans "Отписаться от новостей в категории" %}</a>
                        </button>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </h4>

    {% for post in posts %}
        {% include 'post_card.html' %}
    {% endfor %}
    {% if page_obj.has_other_pages %}
        {% include 'paginator.html' %}
    {% endif %}

{% endblock content %}

NewsPaper/templates/detail.html
{% extends 'default.html' %}
{% load i18n %}
{% load news_filters %}
{% load news_tags %}
{% block title %}{{ content.name|censor }}{% endblock title %}
{% block content %}
    <article class="blog-post">
        <h4 class="pb-1 mb-4 fst-italic">
            {{ content.name|censor }}
            {% if user.id == content.author_post.author_user.id %}
                <div class="container text-end mt-2">
                        <div class="btn-group btn-group-sm" role="group">
                            <button type="button" class="btn btn-success">
                                <a class="text-decoration-none text-light" href="{% url 'news:edit' content.pk %}">{% trans "Редактировать" %}</a>
                            </button>
                            <button type="button" class="btn btn-danger">
                                <a class="text-decoration-none text-light" href="{% url 'news:delete' content.pk %}">{% trans "Удалить" %}</a>
                            </button>
                        </div>
                    </div>
            {% endif %}
        </h4>
        <p class="blog-post-meta">
            {{ content.date_pub }}, {{ content.author_post }}, {% trans "рейтинг автора:" %} {{ content.author_post.author_rate }}
        </p>
        <div class="container-fluid text-center">
            <img class="rounded img-fluid shadow-lg" src="{{ content.content_image.url }}" alt="{{ content.name|censor }}">
        </div>
        <div class="container-fluid mt-4 px-4">{{ content.content|censor|safe }}</div>
        {% for cat in post_category %}
            {% if cat.cat.name not in is_subscribed %}
                <div class="container text-start">
                    <div class="btn-group btn-group-sm" role="group">
                        <button type="button" class="btn btn-primary disabled">{{ cat.cat.name }}</button>
                        <button type="button" class="btn btn-success">
                            <a class="text-decoration-none text-light" href="/subscribe_cat/{{ cat.cat_id }}/">{% blocktrans with cat.cat.name as cat_name %}Подписаться на новости в категории: "{{ cat_name }}"{% endblocktrans %}</a>
                        </button>
                    </div>
                </div>
            {% elif cat.cat.name in is_subscribed %}
                <div class="container text-start">
                    <div class="btn-group btn-group-sm" role="group">
                        <button type="button" class="btn btn-primary disabled">{{ cat.cat.name }}</button>
                        <button type="button" class="btn btn-danger">
                            <a class="text-decoration-none text-light" href="/unsubscribe_cat/{{ cat.cat_id }}/">{% blocktrans with cat.cat.name as cat_name %}Отписаться от новостей в категории: "{{ cat_name }}"{% endblocktrans %}</a>
                        </button>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </article>
    <div class="container text-end">
        <span class="fw-bolder">{% trans "Оцените статью:" %} &nbsp;</span>
        <div class="btn-group btn-group-sm" role="group">
            <button type="button" class="btn btn-secondary">
                <a class="text-decoration-none text-light" href="/dislike_post/{{ content.id }}/">-</a>
            </button>
            <button type="button" class="btn btn-secondary disabled">{{ content.content_rate }}</button>
            <button type="button" class="btn btn-secondary">
                <a class="text-decoration-none text-light" href="/like_post/{{ content.id }}/">+</a>
            </button>
        </div>
    </div>
    <nav {% if current_time.hour >= 19 or  current_time.hour <= 7 %}class="navbar bg-dark text-bg-dark"{% else %}class="navbar bg-light"{% endif %}>
        <div class="container-fluid fw-semibold">
            {% trans "Комментарии" %} ({{ comments.count }})
        </div>
    </nav>
    {% if not comments %}
        <div {% if current_time.hour >= 19 or  current_time.hour <= 7 %}class="alert mx-5 alert-info fw-normal bg-dark text-bg-dark"{% else %}class="alert mx-5 alert-info fw-normal"{% endif %} role="alert">
            {% trans "К этому посту пока нет комментариев..." %}
        </div>
    {% else %}
        {% for comment in comments %}
            <div {% if current_time.hour >= 19 or  current_time.hour <= 7 %}class="alert mx-5 alert-info fw-normal bg-dark text-bg-dark"{% else %}class="alert mx-5 alert-info fw-normal"{% endif %} role="alert">
                <span class="fw-semibold">
                    {{ comment.date_comment }}, {{ comment.user }} {% trans "пишет:" %}
                </span>
                {{ comment.comment|censor }}
                <div class="container text-end">
                    <div class="btn-group btn-group-sm" role="group">
                        <button type="button" class="btn btn-secondary">-</button>
                        <button type="button" class="btn btn-secondary disabled">{{ comment.comment_rate }}</button>
                        <button type="button" class="btn btn-secondary">+</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock content %}

NewsPaper/templates/find.html
{% extends 'default.html' %}

{% load censor %}
{% load news_tags %}

{% block title %}Поиск по сайту{% endblock title %}

{% block content %}
<table class="news">
    <tr>
        <th>Поиск по сайту</th>
    </tr>
    <tr>
        <td>
            <fieldset>
            <table class="find_form">
                <form class="post_filter" action="" method="get">
                {{ postfilter.form.non_field_errors }}
                {{ postfilter.form.name__icontains.errors }}
                    <tr>
                        <td class="label_form">Заголовок содержит:</td>
                        <td class="input_form">{{ postfilter.form.name__icontains }}</td>
                    </tr>
                    <!--
                    <tr>
                        <td class="label_form">В тексте встречается:</td>
                        <td class="input_form">{{ postfilter.form.content__icontains }}</td>
                    </tr>
                    -->
                    <tr>
                        <td class="label_form">Относится к разделам:</td>
                        <td class="input_form">{{ postfilter.form.post_cat }}</td>
                    </tr>
                    <tr>
                        <td class="label_form">Опубликовано после:</td>
                        <td class="input_form">
                            <input
                                id="{{ postfilter.form.date_pub__gt.id_for_label }}"
                                name="{{ postfilter.form.date_pub__gt.name }}"
                                type="datetime-local"
                                value="{{ postfilter.form.date_pub__gt.value }}"
                                class="form-control">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="submit_form"><input type="submit" value="Найти"></td>
                    </tr>
                </form>
            </table>
            </fieldset>
        </td>
    </tr>
</table>
{% if postfilter.form.name__icontains.value or postfilter.form.post_cat.value or postfilter.form.date_pub__gt.value %}
    {% if find %}
        <table class="news">
            <tr>
                <th>Результаты поиска</th>
            </tr>
            <tr>
                <td>
                    <table>
                    {% for post in find %}
                    <tr>
                        <td>
                            <a class="news_title" href="{% url 'news:detail' post.id %}">
                                {{ post.name|censor }}
                            </a>
                            <br>
                            <p>{{ post.content|safe|censor|truncatechars:250 }}</p>
                        </td>
                    </tr>
                    {% endfor %}
                    </table>
                </td>
            </tr>
        </table>
        <div class="pagination">
            {% if page_obj.has_previous %}
                <a href="?{% url_replace page=1 %}"><<&nbsp;</a>
                <a href="?{% url_replace page=page_obj.previous_page_number %}"><&nbsp;</a>
                <a href="?{% url_replace page=1 %}">1</a>
                {% if page_obj.previous_page_number != 1  %}
                    ...
                    <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
                {% endif %}
            {% endif %}

            <span class="current">&nbsp;{{ page_obj.number }}&nbsp;</span>

            {% if page_obj.has_next %}
                <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
                {% if paginator.num_pages != page_obj.next_page_number %}
                    ...
                    <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
                <a href="?{% url_replace page=page_obj.next_page_number %}">&nbsp;></a>
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">&nbsp;>></a>
            {% endif %}
        </div>
    {% else %}
        <p style="text-align: center; font-weight: bolder; color: brown">
            По данному запросу ничего не найдено
        </p>
    {% endif %}
{% endif %}
{% endblock content %}

NewsPaper/templates/navigate.html
{% load i18n %}
{% load tz %}
{% load cache %}
<div class="container-fluid">
  <header class="blog-header lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
          {% if user.id %}
              <p class="pb-0 mb-0">
                  {{ user }}
                  :
                  <a title="{% trans "Профиль" %}" class="link-primary text-decoration-none" href="{% url 'news:profile' user.id %}">{% trans "Профиль" %}</a>
                  :
                  <a title="{% trans "Добавить статью" %}" class="link-primary text-decoration-none" href="{% url 'news:create' %}">{% trans "Добавить статью" %}</a>
              </p>
          {% endif %}
      </div>
      <div class="col-4 text-center">
        {{ current_time }}
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="{% url 'news:search' %}" aria-label="Search">
          <span class="btn btn-outline-info">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
          </span>
        </a>
        &nbsp;
          {% if user.id %}
            <a class="btn btn-outline-danger" href="/accounts/logout/">{% trans "Выход" %}</a>
          {% else %}
            <a class="btn btn-outline-success" href="/accounts/login/">{% trans "Вход" %} | {% trans "Регистрация" %}</a>
          {% endif %}
      </div>
    </div>
  </header>
  <nav {% if current_time.hour >= 19 or  current_time.hour <= 7 %}class="navbar bg-dark text-bg-dark"{% else %}class="navbar bg-light"{% endif %}>
    <div {% if current_time.hour >= 19 or  current_time.hour <= 7 %}class="container-fluid bg-dark text-bg-dark"{% else %}class="container-fluid"{% endif %}>
      <a {% if current_time.hour >= 19 or  current_time.hour <= 7 %}class="navbar-brand fs-6 text-bg-dark"{% else %}class="navbar-brand fs-6"{% endif %} href="{% url 'news:index' %}">{% trans "Главная" %}</a>
      {% for item in category %}
        <a {% if current_time.hour >= 19 or  current_time.hour <= 7 %}class="navbar-brand fs-6 text-bg-dark"{% else %}class="navbar-brand fs-6"{% endif %} href="{% url 'news:category' item.id %}">{{ item.name }}</a>
      {% endfor %}
    </div>
  </nav>
</div>

NewsPaper/templates/nws_art.html
{% extends 'default.html' %}

{% load censor %}
{% load news_tags %}

{% block title %}{{ content.name }}{% endblock title %}

{% block content %}

<table class="news">
    <tr>
        <th class="news_title">
            <h1>
                {{ content.name|censor }}
            </h1>
        </th>
    </tr>
    <tr>
        <td>
            {{ content.content|censor|safe }}
        </td>
    </tr>
</table>
<table class="meta_data">
    <tr>
        <td>
            Автор: {{ content.author_post }}<br>
            Дата публикации: {{ content.date_pub|date:'d.m.Y' }}<br>
            Рейтинг поста/автора: {{ content.content_rate }}/{{ author.author_rate }}
        </td>
    </tr>
    <tr>
        <td class="deledit">
            <a href="{% url 'news:edit' content.pk %}">Изменить</a>
            |
            <a href="{% url 'news:delete' content.pk %}">Удалить</a>
        </td>
    </tr>
</table>
<table class="comment">
    <tr>
        <th>
            Комментарии ({{ comments.count }})
        </th>
    </tr>
    {% if not comments %}
    <tr>
        <td>
            К этому посту пока нет комментариев...
        </td>
    </tr>
    {% else %}
    {% for comment in comments %}
    <tr>
        <td>
            <strong>
                {{ comment.date_comment }}, {{ comment.user}} пишет:
            </strong>
            {{ comment.comment|censor }}
            <div class="comment">
                Рейтинг: {{ comment.comment_rate }}
            </div>
        </td>
    </tr>
    {% endfor %}
    {% endif %}
</table>

{% endblock content %}